const CREATING_FLAG = 0
const PENDING_FLAG = 1
const COOKING_FLAG = 2
const PREPARE_FLAG = 3
const EATING_FLAG = 4
const PAYING_FLAG = 5
const COMPLETE_FLAG = 6

const ACCOUNT_CUSTOMER = 0
const ACCOUNT_WAITER = 1
const ACCOUNT_CASHIER = 2
const ACCOUNT_CHEF = 3
const ACCOUNT_ADMIN = 4

module.exports = {
    CREATING_FLAG, PENDING_FLAG, COOKING_FLAG, 
    PREPARE_FLAG, EATING_FLAG, PAYING_FLAG, COMPLETE_FLAG,
    
    ACCOUNT_CUSTOMER, ACCOUNT_WAITER, ACCOUNT_CASHIER, 
    ACCOUNT_CHEF, ACCOUNT_ADMIN
}